import { test, expect, type Page, type Request } from '@playwright/test';

async function waitForReactMount(page: Page): Promise<void> {
  await page.waitForFunction(
    () => {
      const root = document.getElementById('root');
      if (!root) return false;
      if (document.getElementById('skeleton')) return false;
      return root.children.length > 0;
    },
    { timeout: 10_000 },
  );
}

function isCreateChannelRequest(req: Request): boolean {
  return req.method() === 'POST' && req.url().includes('/api/channels');
}

test.describe('channel wizard', () => {
  test('describe mode materializes the generated channel via POST /api/channels', async ({ page }) => {
    const createRequests: string[] = [];

    await page.route('**/api/channels/generate', async (route) => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          slug: 'generated-probe',
          name: 'Generated Probe',
          description: 'Generated by test',
        }),
      });
    });

    await page.route('**/api/channels', async (route) => {
      if (isCreateChannelRequest(route.request())) {
        createRequests.push(route.request().postData() ?? '');
      }
      await route.continue();
    });

    await page.goto('/#/channels/general');
    await waitForReactMount(page);

    await page.getByRole('button', { name: /new channel/i }).click();
    await expect(page.locator('.channel-wizard-modal')).toBeVisible({ timeout: 10_000 });

    await page.locator('#channel-prompt').fill('Create a launch war room for testing');
    await page.locator('.channel-wizard-footer .btn-primary').click();

    await expect.poll(() => createRequests.length).toBe(1);
    expect(createRequests[0]).toContain('"action":"create"');
    expect(createRequests[0]).toContain('"slug":"generated-probe"');
    expect(createRequests[0]).toContain('"name":"Generated Probe"');
  });
});
